# Generated by Django 5.2.8 on 2025-11-07 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='campus',
            field=models.CharField(choices=[('DIA', 'Diamantina'), ('JAN', 'Janaúba'), ('UNA', 'Unaí'), ('MUC', 'Mucuri')], default='DIA', max_length=3, verbose_name='Campus de Atuação (Requisito Onde)'),
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Habilidade/Competência')),
                ('descricao', models.TextField(blank=True, verbose_name='Breve descrição da habilidade')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='habilidades_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários que possuem esta habilidade')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades (O Quê)',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Demanda/Projeto')),
                ('proposito', models.TextField(verbose_name='Descrição e Propósito da Colaboração (Requisito Por Quê)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação (Requisito Quando)')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto para Colaboração'), ('CONCLUIDO', 'Concluído/Atendido'), ('OPINIAO', 'Em Fase de Coleta de Opinião')], default='ABERTO', max_length=20)),
                ('habilidades_requeridas', models.ManyToManyField(blank=True, related_name='projetos_requerem', to='habilidades.habilidade', verbose_name='Habilidades necessárias')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_propostos', to=settings.AUTH_USER_MODEL, verbose_name='Proponente da Demanda (Requisito Quem)')),
            ],
            options={
                'verbose_name': 'Projeto/Demanda',
                'verbose_name_plural': 'Projetos/Demandas (O Quê)',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
